# Generated by Django 2.2.9 on 2021-04-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210416_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(default=1, verbose_name='typeid')),
                ('typenames', models.CharField(max_length=32, verbose_name='typenames')),
                ('childtypenames', models.CharField(max_length=255, verbose_name='childtypenames')),
                ('typesort', models.IntegerField(default=1, verbose_name='typesort')),
            ],
        ),
    ]
