# Generated by Django 2.2.9 on 2021-04-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_foodtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtype',
            name='childtypenames',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='typeid',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='typenames',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='typesort',
        ),
        migrations.RemoveField(
            model_name='mainmustbuy',
            name='trackid',
        ),
        migrations.RemoveField(
            model_name='mainnav',
            name='trackid',
        ),
        migrations.RemoveField(
            model_name='mainwheel',
            name='trackid',
        ),
        migrations.AddField(
            model_name='foodtype',
            name='child_type_names',
            field=models.CharField(max_length=255, null=True, verbose_name='child_type_names'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='type_id',
            field=models.IntegerField(default=1, null=True, verbose_name='type_id'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='type_name',
            field=models.CharField(max_length=32, null=True, verbose_name='type_name'),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='type_sort',
            field=models.IntegerField(default=1, null=True, verbose_name='type_sort'),
        ),
        migrations.AddField(
            model_name='mainmustbuy',
            name='track_id',
            field=models.IntegerField(default=1, verbose_name='track_id'),
        ),
        migrations.AddField(
            model_name='mainnav',
            name='track_id',
            field=models.IntegerField(default=1, verbose_name='track_id'),
        ),
        migrations.AddField(
            model_name='mainwheel',
            name='track_id',
            field=models.IntegerField(default=1, verbose_name='track_id'),
        ),
    ]
