# Generated by Django 2.2.9 on 2021-04-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_icon',
            field=models.ImageField(upload_to='icons/%Y/%m/%d/'),
        ),
    ]
